---
- block:
    - name: Create configuration directory for Pulp
      file:
        path: '{{ pulp_config_dir }}'
        state: directory
        owner: root
        group: '{{ pulp_group }}'
        mode: 0750
      notify: Restore SELinux contexts on Pulp dirs that must exist

    - name: Create configuration file for Pulp
      template:
        src: settings.py.j2
        dest: '{{ pulp_settings_file }}'
        owner: root
        group: '{{ pulp_group }}'
        mode: 0640
        force: yes

  become: true
