---
# When you updated this, update vagrant/requirements.nested-docker.yaml also.
roles:
  - name: geerlingguy.postgresql
collections:
  - ansible.posix
  - name: community.crypto
    version: ">=1.0.0"
  - community.general
  - community.postgresql
  - mdellweg.filters
