---
# When you updated this, update vagrant/requirements.nested-docker.yaml also.
roles:
  - geerlingguy.postgresql
collections:
  - ansible.posix
  - community.crypto
  - community.general
  - community.postgresql
