---
- hosts: all
  vars:
    paths_to_vars_files:
      - '../../local.{{ ansible_hostname }}-config.yml'
      - '../../local.user-config.yml'
      - '../../example.user-config.yml'
  pre_tasks:
    - name: Load local config
      include_vars: "{{ item }}"
      with_first_found: "{{ paths_to_vars_files }}"

    # The version string below is the highest of all those in roles' metadata:
    # "min_ansible_version". It needs to be kept manually up-to-date.
    - name: Verify Ansible meets min required version
      assert:
        that: "ansible_version.full is version_compare('2.9', '>=')"
        msg: >
          "You must update Ansible to at least 2.9 to use this version of Pulp 3 Installer."

    # FIPS boxes require 2.10
    - name: Verify Ansible meets min required version for FIPS boxes
      assert:
        that: "ansible_version.full is version_compare('2.10', '>=')"
        msg: >
          "You must update Ansible to at least 2.10 to use this version of Pulp 3 Installer."
      when: "'fips' in ansible_fqdn"

    # TODO: Delete this task after 2023-05
    # Previously vagrant logic installed the collection to this path.
    # We now want to use the "./roles" folders instaed, for compatibility with
    # molecule which uses "./roles", but has the problem of the installed
    # collection overriding it.
    - name: Delete installed pulp.pulp_installer collection
      file:
        state: absent
        path: "~/.ansible/collections/ansible_collections/pulp/pulp_installer"
      delegate_to: localhost
      become_user: "{{ lookup('env', 'USER') }}"

    - name: Check (S3) storage backend is configured.
      assert:
        that:
          - pulp_settings.aws_access_key_id is defined
          - pulp_settings.aws_secret_access_key is defined
          - pulp_settings.aws_storage_bucket_name is defined
          - pulp_settings.aws_default_acl is defined
          - pulp_settings.s3_use_sigv4 is defined
          - pulp_settings.aws_s3_signature_version is defined
          - pulp_settings.aws_s3_addressing_style is defined
          - pulp_settings.aws_s3_region_name is defined
          - pulp_settings.media_root is defined
          - pulp_settings.default_file_storage is defined
      when: pulp_install_object_storage is defined and pulp_install_object_storage == "s3"

    - name: Check (Azure) storage backend is configured.
      assert:
        that:
          - pulp_settings.azure_account_name is defined
          - pulp_settings.azure_container is defined
          - pulp_settings.azure_account_key is defined
          - pulp_settings.azure_url_expiration_secs is defined
          - pulp_settings.azure_overwrite_files is defined
          - pulp_settings.azure_location is defined
          - pulp_settings.default_file_storage is defined
      when: pulp_install_object_storage is defined and pulp_install_object_storage == "azure"

    - include_tasks: pre_tasks/vagrant-workarounds.yml
    - include_tasks: pre_tasks/selinux-workarounds.yml

  roles:
    - pulp_all_services
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
