---
# We cannot pass wildcards to the systemd module, so we have
# this hack for our dynamic include_roles users.
#
# The handlers will be flushed during pulp_database, before
# pulp_workers is called. But said users' ansible does not know
# the number of pulp-workers yet.
#
# Later one, the Pulp services *should* be refactored into a
# systemd multi-service app. That would mean a single task would
# restart all of Pulp.
- name: Reload systemd
  systemd:
    daemon_reload: true
  become: true

- name: Restart all pulpcore* services
  command: systemctl restart pulpcore*
  become: true
