---
- name: Ensure pulp is part of group redis
  user:
    name: '{{ pulp_user }}'
    groups: redis
    append: true

- name: Ensure Redis will not listen on a TCP socket
  lineinfile:
    path: '{{ pulp_redis_conf_file | default(_pulp_redis_conf_file) }}'
    regexp: '{{ __pulp_redis_setting.regexp }}'
    line: '{{ __pulp_redis_setting.line }}'
  loop:
    - regexp: '^port '
      line: 'port 0'
    - regexp: '^unixsocket '
      line: 'unixsocket {{ pulp_redis_bind | replace("unix:", "") }}'
    - regexp: '^unixsocketperm '
      line: 'unixsocketperm 775'
  loop_control:
    loop_var: __pulp_redis_setting
  notify: restart redis
