---

- name: Install service files
  template:
    src: '{{ item }}.service.j2'
    dest: '/lib/systemd/system/{{ item }}.service'
    owner: root
    group: root
    mode: 0644
  with_items:
    - pulp_web
    - pulp_resource_manager
    - pulp_worker@
  notify: 'reload systemd and restart {{ item }}'

- name: Set the pulp_web service state
  service:
    name: pulp_web.service
    state: '{{ pulp_web_state }}'
    enabled: '{{ pulp_web_enabled }}'

- name: Set the pulp_resource_manager service state
  service:
    name: pulp_resource_manager.service
    state: '{{ pulp_resource_manager_state }}'
    enabled: '{{ pulp_resource_manager_enabled }}'

- name: Set pulp_worker service states
  service:
    name: 'pulp_worker@{{ item.key }}.service'
    state: '{{ item.value.state }}'
    enabled: '{{ item.value.enabled }}'
  with_dict: '{{ pulp_workers }}'
