---
- hosts: all
  force_handlers: True
  collections:
    - pulp.pulp_installer
  pre_tasks:
    # The version string below is the highest of all those in roles' metadata:
    # "min_ansible_version". It needs to be kept manually up-to-date.
    - name: Verify Ansible meets min required version
      assert:
        that: "ansible_version.full is version_compare('2.8', '>=')"
        msg: >
          "You must update Ansible to at least 2.8 to use this version of Pulp 3 Installer."
  tasks:
    - name: Dynamically include individual roles
      include_role:
        name: "{{ roleinputvar }}"
      loop:
        - pulp_database
        - pulp_redis
        - pulp_database_config
        - pulp_api
        - pulp_content
        - pulp_workers
        - pulp_health_check
        - pulp_webserver
      loop_control:
        loop_var: roleinputvar
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
