---
- block:
  - name: Ensure tar is available for galaxy-importer
    package:
      name: tar
      state: present

  - name: Create galaxy-importer directory
    file:
      path: "/etc/galaxy-importer/"
      state: directory
      mode: '0755'

  - name: Write galaxy-importer config
    template:
      src: galaxy-importer.cfg.j2
      dest: /etc/galaxy-importer/galaxy-importer.cfg
      mode: '0644'

  become: true
