---
- name: Check if container signing service gpg key exists
  stat:
    path: "{{ pulp_certs_dir }}/container_signing_service.gpg"
  register: stat_container_signing_service

- name: Generate container signing service gpg key  # noqa no-changed-when deprecated-command-syntax
  shell: |
    mkdir /tmp/container_gpg
    cat >/tmp/gpg.txt <<EOF
    %echo Generating a basic OpenPGP key
    Key-Type: default
    Key-Length: 4096
    Subkey-Type: default
    Subkey-Length: default
    Name-Real: Container Signing Service
    Name-Comment: with no passphrase
    Name-Email: joe@foo.bar
    Expire-Date: 0
    %no-ask-passphrase
    %no-protection
    # Do a commit here, so that we can later print "done" :-)
    %commit
    %echo done
    EOF
    GNUPGHOME=/tmp/container_gpg gpg --batch --gen-key /tmp/gpg.txt
    GNUPGHOME=/tmp/container_gpg gpg --output {{ pulp_certs_dir }}/container_signing_service.gpg --armor --export-secret-key
    GNUPGHOME=/tmp/container_gpg gpg --output {{ pulp_certs_dir }}/container_signing_service.asc --armor --export
    rm -rf /tmp/container_gpg
  when: not stat_container_signing_service.stat.exists

- name: Check if sample container signing service script exists
  stat:
    path: "{{ pulp_scripts_dir }}/container_sign.sh"
  register: stat_container_sign_script

- name: Create sample container signing service script
  copy:
    src: container_sign.sh
    dest: "{{ pulp_scripts_dir }}/container_sign.sh"
    mode: 0755
  when: not stat_container_sign_script.stat.exists
