---
- name: Check if collection signing service gpg key exists
  stat:
    path: "{{ pulp_certs_dir }}/galaxy_signing_service.gpg"
  register: stat_collection_signing_service

- name: Generate collection signing service gpg key  # noqa no-changed-when deprecated-command-syntax
  shell: |
    mkdir /tmp/collection_gpg
    cat >/tmp/gpg.txt <<EOF
    %echo Generating a basic OpenPGP key
    Key-Type: default
    Key-Length: 4096
    Subkey-Type: default
    Subkey-Length: default
    Name-Real: Collection Signing Service
    Name-Comment: with no passphrase
    Name-Email: joe@foo.bar
    Expire-Date: 0
    %no-ask-passphrase
    %no-protection
    # Do a commit here, so that we can later print "done" :-)
    %commit
    %echo done
    EOF
    GNUPGHOME=/tmp/collection_gpg gpg --batch --gen-key /tmp/gpg.txt
    GNUPGHOME=/tmp/collection_gpg gpg --output {{ pulp_certs_dir }}/galaxy_signing_service.gpg --armor --export-secret-key
    GNUPGHOME=/tmp/collection_gpg gpg --output {{ pulp_certs_dir }}/galaxy_signing_service.asc --armor --export
    rm -rf /tmp/collection_gpg
  when: not stat_collection_signing_service.stat.exists

- name: Check if sample collection signing service script exists
  stat:
    path: "{{ pulp_scripts_dir }}/collection_sign.sh"
  register: stat_collection_sign_script

- name: Create sample collection signing service script (EL7)
  copy:
    src: collection_sign.sh.el7
    dest: "{{ pulp_scripts_dir }}/collection_sign.sh"
    mode: 0755
  when:
    - __pulp_os_family == 'RedHat'
    - ansible_facts.distribution_major_version|int == 7
    - not stat_collection_sign_script.stat.exists

- name: Create sample collection signing service script
  copy:
    src: collection_sign.sh
    dest: "{{ pulp_scripts_dir }}/collection_sign.sh"
    mode: 0755
  when:
    - (__pulp_os_family != 'RedHat') or (ansible_facts.distribution_major_version|int != 7)
    - not stat_collection_sign_script.stat.exists
