---
- name: Preparing loogger
  block:
  - name: Create Galaxy api access log file
    file:
      path: '/var/log/galaxy_api_access.log'
      state: touch
      owner: '{{ pulp_user }}'
      group: '{{ pulp_group }}'
      mode: "u+rw"
      serole: _default
      setype: _default
      seuser: _default
    tags:
      - molecule-idempotence-notest

  - name: Populate service facts
    service_facts:

  - name: Set environment variable for Galaxy api access logging
    lineinfile:
      path: /etc/default/pulpcore-api
      regexp: '^GALAXY_ENABLE_API_ACCESS_LOG='
      line: GALAXY_ENABLE_API_ACCESS_LOG={{ pulp_settings['galaxy_enable_api_access_log'] | default(False) }}
      create: True
      owner: '{{ pulp_user }}'
      group: '{{ pulp_group }}'
      mode: "u+rw"
      serole: _default
      setype: _default
      seuser: _default
    notify: Restart pulpcore-api.service post galaxy

  become: true
