---
galaxy_info:
  author: Pulp Team
  description: A role to setup a redis service for use by Pulp 3
  issue_tracker_url: https://github.com/pulp/pulp_installer/issues/new
  license: GPL-2.0-or-later
  company: Red Hat
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "33"
        - "34"
        - "35"
        - "36"
  galaxy_tags:
    - pulp
    - pulpcore
dependencies: []
