---
- hosts: all
  tasks:
    - name: Hot patch redis-server service for docker operation (Debian)
      copy:
        src: debian-redis-server.service
        dest: /etc/systemd/system/redis-server.service
      when: ansible_distribution == "Debian"

    # These 2 tasks exist in playbooks/example-use/playbook.yml , but we need
    # them here so that yum/dnf commands can succeed.
    - name: Check if pulpcore repo exists
      stat:
        path: /etc/yum.repos.d/pulpcore.repo
      register: pulpcorerepo

    - name: Remove pulpcore fedorapeople
      lineinfile:
        path: /etc/yum.repos.d/pulpcore.repo
        regexp: 'fedorapeople'
        line: "baseurl = {{ pulp_pkg_repo }}"
      when: pulpcorerepo.stat.exists

    - name: Ensure dnf is not installed, which would conflict with ansible-pulp-rpm
      yum:
        name:
          - python2-dnf
          - python2-libdnf
          - dnf-data
          - libdnf
        state: absent
        use_backend: yum
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version|int == 7

    # Needed because Debian 10 is now "oldstable"
    - name: Allow release info change
      lineinfile:
        path: /etc/apt/apt.conf.d/99releaseinfochange
        state: present
        create: yes
        line: Acquire::AllowReleaseInfoChange::Suite "true";
      when: ansible_facts.distribution == 'Debian' and ansible_facts.distribution_major_version == '10'

    # Needed for the 1st time we run a package or apt task
    - name: Update apt package index
      apt:
        update_cache: yes
      when: ansible_facts.distribution == 'Debian' and ansible_facts.distribution_major_version == '10'
      # We aren't really changing the system, so let's minimize the reporting of CHANGED tasks.
      changed_when: False

    - name: Migrate CentOS 8 to CentOS Stream 8
      block:
        - name: Get latest CentOS 8 GPG keys and its temporary dependency
          dnf:
            name:
              - https://vault.centos.org/8.5.2111/BaseOS/x86_64/os/Packages/centos-gpg-keys-8-3.el8.noarch.rpm
              - https://vault.centos.org/8.5.2111/BaseOS/x86_64/os/Packages/centos-linux-repos-8-3.el8.noarch.rpm
            disablerepo:
              - baseos
              - appstream
              - extras
              - BaseOS
              - AppStream
              - Extras
              - PowerTools
              - pulpcore
          when:
            - ansible_distribution == "CentOS"
            - ansible_distribution_version in ["8.2","8.3","8.4"]

        - name: Switch to CentOS 8 Stream repos
          command: dnf -y --disablerepo * --enablerepo extras swap centos-linux-repos centos-stream-repos

        - name: Finish CentOS 8 Stream migration
          dnf:
            name:
              - centos-stream-release
              - centos-gpg-keys
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_version in ["8.2","8.3","8.4","8.5"]

    # Probably needed due to a mismatch of systemd versions/capabilities between the Ubuntu GHA
    # host and the container
    - name: Update systemd to fix the Ansible systemd module, and inspec (verify phase)
      package:
        name: systemd
        state: latest  # noqa 403
      # Fixes ansible systemd module on Debian & Fedora, fixes inspec on EL8
      when: (ansible_facts.distribution == 'Debian' and ansible_facts.distribution_major_version == '10') or
            (ansible_facts.distribution == 'Fedora' and ansible_facts.distribution_major_version == '31') or
            (ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version == '8')

    # Possibly not necessary
    - name: Make the systemd update take effect
      systemd:
        daemon_reexec: true
