---
__pulp_apache_url: 'localhost'
pulp_install_plugins_normalized_yml: |-
  {% for key, value in pulp_install_plugins.items() %}
  {{ key.replace('_', '-') }}: {{ value | to_json }}
  {% endfor %}
pulp_install_plugins_normalized: "{{ pulp_install_plugins_normalized_yml | from_yaml }}"

__pulp_database_config_host: "{{ hostvars['localhost']['pulp_database_config_host'] | default(inventory_hostname) }}"
__pulp_install_dir: "{{ hostvars[__pulp_database_config_host]['pulp_install_dir'] }}"
__pulp_install_source: "{{ hostvars[__pulp_database_config_host]['pulp_install_source'] }}"
__pulp_python_interpreter: "{{ hostvars[__pulp_database_config_host]['pulp_python_interpreter'] }}"
__pulp_python_path: "{{ hostvars[__pulp_database_config_host]['pulp_python_path'] | default('') }}"
__pulp_subject_alt_name: '{{ pulp_webserver_httpd_servername | regex_search("^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$") | ternary("IP:" + pulp_webserver_httpd_servername, "DNS:" + pulp_webserver_httpd_servername) }}'
