# Molecule managed

# This Dockerfile prepares the image for {{ item.image }} to be used in molecule tests for the
# ansible-pulp role. The main process should be systemd, to mimic an installation where services
# can be installed and controlled. Systemd seems to be able to detect that it is being run in a
# container context, and starts very few services. There is generally no need to delete any
# files from /{etc,lib}/systemd/*. Exceptions though:
#
# /usr/lib/tmpfiles.d/postgresql.conf
# Workaround geerlingguy.postgresql setting different perms on
# /var/run/postgresql than Fedora & derivatives want.
# A timer than runs 15 mins since boot makes little sense for a container
# anyway. It's not a persistent system.

FROM {{ item.image }}

ENV container docker

{% if item.name.startswith('centos') -%}

RUN yum install -y epel-release ;\
yum makecache fast ;\
yum update -y ;\
yum install -y \
  bash \
  firewalld \
  iptables \
  jemalloc \
  python \
  python2-dnf \
  selinux-policy \
  sudo \
  which \
  yum-plugin-ovl \
  ;\
sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf ;\
yum clean all ;\
echo 'd /var/run/postgresql 2775 postgres postgres -' >  /etc/tmpfiles.d/postgresql.conf
{% elif item.name.startswith('debian') -%}

ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update &&\
apt-get -y install \
  kmod \
  net-tools \
  systemd \
  systemd-sysv \
  &&\
rm /sbin/modprobe &&\
ln -s /bin/true /sbin/modprobe &&\
apt-get -y install \
  bash \
  firewalld \
  iptables \
  python3 \
  python3-setuptools \
  sudo \
  &&\
apt-get clean &&\
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&\
systemctl enable firewalld
{% elif item.name.startswith('fedora') -%}

RUN dnf makecache ;\
dnf --assumeyes install \
  bash \
  firewalld \
  iptables \
  jemalloc \
  glibc-langpack-en \
  python3 \
  python3-dnf \
  python3-firewall \
  selinux-policy \
  sudo \
  which \
  ;\
dnf clean all ;\
echo 'd /var/run/postgresql 2775 postgres postgres -' >  /etc/tmpfiles.d/postgresql.conf
{%- endif %}

# Disable requiretty.
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# systemd uses this as a termination signal; we want to shutdown the containers nicely...
STOPSIGNAL SIGRTMIN+3

CMD ["{{ item.command }}"]
