# Molecule managed

# This Dockerfile prepares the image for {{ item.image }} to be used in molecule tests for the
# pulp_installer role. The main process should be systemd, to mimic an installation where services
# can be installed and controlled. Systemd seems to be able to detect that it is being run in a
# container context, and starts very little services. There is no need to delete any files from
# /{etc,lib}/systemd/*.
{% if item.name.startswith('fedora') -%}
FROM registry.fedoraproject.org/{{ item.image }}
{% else -%}
FROM {{ item.image }}
{%- endif %}

ENV container docker

{% if item.name.startswith('centos-7') -%}

RUN yum install -y epel-release &&\
yum makecache fast &&\
yum update -y &&\
yum install -y \
  bash \
  jemalloc \
  python \
  selinux-policy \
  sudo \
  which \
  yum-plugin-ovl \
  &&\
sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf &&\
yum clean all
{% elif item.name.startswith('debian') -%}

ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update &&\
apt-get -y install \
  kmod \
  net-tools \
  systemd \
  systemd-sysv \
  &&\
rm /sbin/modprobe &&\
ln -s /bin/true /sbin/modprobe &&\
apt-get -y install \
  bash \
  python3 \
  python3-setuptools \
  sudo \
  &&\
apt-get clean &&\
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
{% else -%}
# fedora or centos-8

RUN grep -v "CentOS" /etc/redhat-release || dnf install -y epel-release &&\
dnf makecache &&\
dnf update -y &&\
dnf --assumeyes install \
  bash \
  jemalloc \
  glibc-langpack-en \
  python3 \
  python3-dnf \
  python3-setuptools \
  selinux-policy \
  selinux-policy-targeted \
  sudo \
  which \
  &&\
dnf clean all
{%- endif %}

# Disable requiretty.
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# systemd uses this as a termination signal; we want to shutdown the containers nicely...
STOPSIGNAL SIGRTMIN+3

CMD ["{{ item.command }}"]
