---
# NOTE: Keep in sync with pulp_database/tasks/ambiguously-named.repo.yml
# NOTE: __pulp_common_repo_enabled is named specific to this version of ambiguously-named.repo.yml , since it
# would bleed over into other runs of other ambiguously-named.repo.yml files.

- name: "Determine which file in /etc/yum.repos.d/ has the {{ __ambiguously_named_repo }} repo"
  shell: grep -l -E "^\[{{ __ambiguously_named_repo }}\]" /etc/yum.repos.d/*.repo
  register: repo_file
  changed_when: false
  failed_when: false
  check_mode: False

- name: "Enable the {{ __ambiguously_named_repo }} repo"
  ini_file:
    path: "{{ repo_file.stdout }}"
    section: "{{ __ambiguously_named_repo }}"
    option: enabled
    value: "1"
    no_extra_spaces: true
    mode: '0644'
  when: repo_file.rc == 0
  register: "{{ reg_variable }}"
  become: true
