# Molecule managed

FROM {{ item.image }}

ENV container docker

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

# CentOS
RUN if [[ "$(source /etc/os-release && echo "$ID")" == 'centos' ]]; then \
  yum install -y epel-release ;\
  yum makecache fast ;\
  yum update -y ;\
  yum install -y python sudo python2-dnf yum-plugin-ovl bash which \
                 selinux-policy firewalld jemalloc ;\
  sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf ;\
  yum clean all ;\
elif [[ "$(source /etc/os-release && echo "$ID")" == 'fedora' ]]; then \
  dnf makecache ;\
  dnf --assumeyes install python sudo python2-dnf bash which selinux-policy \
                          python-firewall firewalld jemalloc ;\
  dnf clean all ;\
fi

# Disable requiretty.
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers


VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]

CMD ["/usr/sbin/init"]
