---
- hosts: centos-8
  force_handlers: True
  collections:
    - pulp.pulp_installer
  pre_tasks:
    - name: Install /usr/sbin/ip so that Ansible can enumerate the NICs
      dnf:
        name: iproute
    - setup:
  tasks:
    - name: Dynamically include individual roles
      include_role:
        name: "{{ roleinputvar }}"
      loop:
        - pulp_database
        - pulp_redis
      loop_control:
        loop_var: roleinputvar
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings

- hosts: all
  force_handlers: True
  collections:
    - pulp.pulp_installer
  # pre_tasks:
  #   - name: Add IP address of centos-8 to the hosts
  #     lineinfile:
  #       dest: /etc/hosts
  #       regexp: ".*centos-8$"
  #       line: "{{ hostvars['centos-8']['ansible_eth0']['ipv4']['address'] }} centos-8 "
  #       state: present
  tasks:
    - name: Dynamically include individual roles
      include_role:
        name: "{{ roleinputvar }}"
      loop:
        - pulp_database_config
        - pulp_api
        - pulp_content
        - pulp_workers
        - pulp_health_check
        - pulp_webserver
      loop_control:
        loop_var: roleinputvar
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
