---
- hosts: all
  collections:
    - pulp.pulp_installer
  pre_tasks:
    # The version string below is the highest of all those in roles' metadata:
    # "min_ansible_version". It needs to be kept manually up-to-date.
    - name: Verify Ansible meets min required version
      assert:
        that: "ansible_version.full is version_compare('2.8', '>=')"
        msg: >
          "You must update Ansible to at least 2.8 to use this version of Pulp 3 Installer."
  tasks:
    - debug:
        var: groups
    - debug:
        var: inventory_hostname

    - name: Dynamically include DB roles
      include_role:
        name: pulp_common
      when: inventory_hostname in groups.pulp

    - name: Dynamically include DB roles
      include_role:
        name: "{{ roleinputvar }}"
      loop:
        - pulp_database
        - pulp_database_config
      loop_control:
        loop_var: roleinputvar
      when: inventory_hostname in groups.db

    - name: Dynamically include content roles
      include_role:
        name: "{{ roleinputvar }}"
      loop:
        - pulp_redis
        - pulp_content
      loop_control:
        loop_var: roleinputvar
      when: inventory_hostname in groups.content

    - name: Dynamically include api roles
      include_role:
        name: "{{ roleinputvar }}"
      loop:
        - pulp_api
        - pulp_health_check
        - pulp_webserver
      loop_control:
        loop_var: roleinputvar
      when: inventory_hostname in groups.api

    - name: Dynamically include worker roles
      include_role:
        name: "{{ roleinputvar }}"
      loop:
        - pulp_resource_manager
        - pulp_workers
      loop_control:
        loop_var: roleinputvar
      when: inventory_hostname in groups.worker
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
