---
- name: Install requirements for building docs
  pip:
    requirements: '{{ pulp_source_dir }}/doc_requirements.txt'
    state: present
    virtualenv: '{{ pulp_install_dir }}'
    virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
  when: pulp_source_dir is defined

- name: Install pulpcore requirements for testing locally
  pip:
    requirements: '{{ pulp_source_dir }}/test_requirements.txt'
    state: present
    virtualenv: '{{ pulp_install_dir }}'
    virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
  when: pulp_source_dir is defined
  environment:
    SETUPTOOLS_USE_DISTUTILS: stdlib

- name: Install plugin requirements for testing locally
  pip:
    requirements: '{{ item.value.source_dir }}/functest_requirements.txt'
    state: present
    virtualenv: '{{ pulp_install_dir }}'
    virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
  with_dict: '{{ pulp_install_plugins_normalized }}'
  when: item.value.source_dir is defined
  environment:
    SETUPTOOLS_USE_DISTUTILS: stdlib
  ignore_errors: yes  # noqa ignore-errors

- name: Install requirements for developer scripts
  pip:
    requirements: '{{ pulp_source_dir }}/dev_requirements.txt'
    state: present
    virtualenv: '{{ pulp_install_dir }}'
    virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
  when: pulp_source_dir is defined

- name: Install requirements for Azure/S3 tests
  pip:
    name: django-storages[boto3, azure]>=1.12.2
    state: present
    virtualenv: '{{ pulp_install_dir }}'
    virtualenv_command: '{{ pulp_python_interpreter }} -m venv'

- name: Install HTTPie and JWT authentication plugin
  pip:
    name:
      - httpie
      - httpie-jwt-auth
    state: present
    virtualenv: '{{ pulp_install_dir }}'
    virtualenv_command: '{{ pulp_python_interpreter }} -m venv'

  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded
  notify: Collect static content
...
