---
dependency:
  name: galaxy
# This yaml anchor is ignored by molecule, but can be reused in yaml
# It is ignored in the dependency section, and cannot be a top-level section
  .platform_base: &platform_base
    privileged: False
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      # Fixes issues accessing .so files under /tmp during pip builds.
      # https://github.com/docker/compose/issues/1339
      - /tmp:exec,mode=1777
      - /run
      - /run/lock
    capabilities:
      - NET_ADMIN
      - NET_RAW
    pre_build_image: true
driver:
  name: docker
lint: |
    ansible-lint
platforms:
  - <<: *platform_base
    name: pulp-api1
    image: ghcr.io/pulp/molecule_centos7
    command: /sbin/init
  - <<: *platform_base
    name: pulp-api2
    image: ghcr.io/pulp/molecule_centosstream8
    command: /sbin/init
  - <<: *platform_base
    name: pulp-content
    image: ghcr.io/pulp/molecule_centosstream9
    command: /sbin/init
  - <<: *platform_base
    name: pulp-database
    image: ghcr.io/pulp/molecule_rocky8
    command: /sbin/init
  - <<: *platform_base
    name: pulp-redis
    image: ghcr.io/pulp/molecule_debian11
    command: /sbin/init
  - <<: *platform_base
    name: pulp-webserver
    image: ghcr.io/pulp/molecule_fedora36
    command: /usr/sbin/init
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: $PWD/build/collections:~/.ansible/collections:/usr/share/ansible/collections # for ansible >= 2.10.0.dev0
    ANSIBLE_COLLECTIONS_PATHS: $PWD/build/collections:~/.ansible/collections:/usr/share/ansible/collections
    ANSIBLE_CALLBACKS_ENABLED: "profile_tasks,profile_roles"
    CALLBACKS_ENABLED: "profile_tasks,profile_roles"
  config_options:
    defaults:
      stdout_callback: debug
      callback_enabled: profile_tasks
  inventory:
    links:
      group_vars: ../scenario_resources/group_vars/
scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
verifier:
  name: ansible
  directory: tests
