---
- name: Ensure python-cryptography is installed
  package:
    name: '{{ pulp_python_cryptography }}'
  become: true

- name: Look for CA certificate
  stat:
    path: '{{ pulp_certs_dir }}/root.crt'
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: __pulp_webserver_ca_cert

- name: Generate CA
  block:
    - name: Generate CA key
      openssl_privatekey:
        path: '{{ pulp_certs_dir }}/root.key'
        serole: _default
        setype: _default
        seuser: _default

    - name: Generate CA CSR
      openssl_csr:
        path: '{{ pulp_certs_dir }}/root.csr'
        privatekey_path: '{{ pulp_certs_dir }}/root.key'
        common_name: '{{ pulp_webserver_httpd_servername }}'
        organization_name: Pulp
        country_name: US
        basic_constraints: 'CA:TRUE'
        serole: _default
        setype: _default
        seuser: _default

    - name: Generate CA certificate
      x509_certificate:
        path: '{{ pulp_certs_dir }}/root.crt'
        csr_path: '{{ pulp_certs_dir }}/root.csr'
        privatekey_path: '{{ pulp_certs_dir }}/root.key'
        provider: selfsigned
        serole: _default
        setype: _default
        seuser: _default
  when: not __pulp_webserver_ca_cert.stat.exists

- name: Look for webserver certificate
  stat:
    path: '{{ pulp_certs_dir }}/pulp_webserver.crt'
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: __pulp_webserver_cert

- name: Generate webserver certificate
  block:
    - name: Generate private keys
      openssl_privatekey:
        path: '{{ pulp_certs_dir }}/pulp_webserver.key'
        owner: root
        group: "{{ pulp_group }}"
        serole: _default
        setype: _default
        seuser: _default

    - name: Generate CSRs standalone
      openssl_csr:
        path: '{{ pulp_certs_dir }}/pulp_webserver.csr'
        privatekey_path: '{{ pulp_certs_dir }}/pulp_webserver.key'
        common_name: '{{ pulp_webserver_httpd_servername }}'
        subject_alt_name: 'DNS:{{ pulp_webserver_httpd_servername }}'
        key_usage:
          - keyEncipherment
          - dataEncipherment
        extended_key_usage:
          - serverAuth
        owner: root
        group: "{{ pulp_group }}"
        serole: _default
        setype: _default
        seuser: _default

    - name: Generate certificates
      x509_certificate:
        path: '{{ pulp_certs_dir }}/pulp_webserver.crt'
        csr_path: '{{ pulp_certs_dir }}/pulp_webserver.csr'
        privatekey_path: '{{ pulp_certs_dir }}/pulp_webserver.key'
        provider: ownca
        ownca_path: '{{ pulp_certs_dir }}/root.crt'
        ownca_privatekey_path: '{{ pulp_certs_dir }}/root.key'
        ownca_not_after: '+824d'
        owner: root
        group: "{{ pulp_group }}"
        serole: _default
        setype: _default
        seuser: _default
      notify: reload {{ pulp_webserver_server }}
  when: not __pulp_webserver_cert.stat.exists

- name: Cleanup CSR files
  file:
    path: '{{ pulp_certs_dir }}/{{ __pulp_webserver_csr_path }}'
    state: absent
  loop:
    - root.csr
    - pulp_webserver.csr
  loop_control:
    loop_var: __pulp_webserver_csr_path
