---
# Test upgrade to specific micro versions
- hosts: all
  force_handlers: True
  tasks:
    - set_fact:
        pulpcore_version: "3.14.17"
        prereq_pip_packages:
          - Jinja2
          - pygments
    - set_fact:
        pulp_install_plugins:
          pulp_file:
            version: "1.8.2"
          pulp_rpm:
            version: "3.14.15"
      when: ansible_facts.os_family == 'RedHat'
    - set_fact:
        pulp_install_plugins:
          pulp_file:
            version: "1.8.2"
      when: ansible_facts.os_family == 'Debian'
    - include_role:
        name: pulp_all_services
    - name: Obtain list of packages & versions in the venv after install
      pip_package_info:
        clients: "/usr/local/lib/pulp/bin/pip"
      register: pip_pkgs
    - name: Assert pulpcore==3.14.17, pulp-file==1.8.2
      assert:
        that:
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulpcore'][0].version is version("3.14.17", "=")
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulp-file'][0].version is version("1.8.2", "=")
    - name: Assert pulp-rpm==3.14.15
      assert:
        that:
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulp-rpm'][0].version is version("3.14.15", "=")
      when: ansible_facts.os_family == 'RedHat'
# Test not updating (upgrade=false on a branch)
- hosts: all
  force_handlers: True
  tasks:
    - set_fact:
        pulpcore_version: "3.14"
        pulpcore_update: false
    - set_fact:
        pulp_install_plugins:
          pulp_file:
            version: "1.8"
            upgrade: false
          pulp_rpm:
            version: "3.14"
            upgrade: false
      when: ansible_facts.os_family == 'RedHat'
    - set_fact:
        pulp_install_plugins:
          pulp_file:
            version: "1.8"
            upgrade: fasle
      when: ansible_facts.os_family == 'Debian'
    - include_role:
        name: pulp_database_config
    - name: Obtain list of packages & versions in the venv after install
      pip_package_info:
        clients: "/usr/local/lib/pulp/bin/pip"
      register: pip_pkgs
    - name: Assert pulpcore==3.14.17, pulp-file==1.8.2
      assert:
        that:
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulpcore'][0].version is version("3.14.17", "=")
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulp-file'][0].version is version("1.8.2", "=")
    - name: Assert pulp-rpm==3.14.15
      assert:
        that:
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulp-rpm'][0].version is version("3.14.15", "=")
      when: ansible_facts.os_family == 'RedHat'
# Test updates (upgrade=true on a branch, also add pulp-container)
- hosts: all
  force_handlers: True
  tasks:
    - set_fact:
        pulpcore_version: "3.14"
        pulpcore_update: true
    - set_fact:
        pulp_install_plugins:
          pulp_file:
            version: "1.8"
            upgrade: true
          pulp_rpm:
            version: "3.14"
            upgrade: true
          pulp_container:
            version: "2.8"
            upgrade: true
      when: ansible_facts.os_family == 'RedHat'
    - set_fact:
        pulp_install_plugins:
          pulp_file:
            version: "1.8"
            upgrade: true
          pulp_container:
            version: "2.8"
            upgrade: true
      when: ansible_facts.os_family == 'Debian'
    - include_role:
        name: pulp_database_config
    - name: Obtain list of packages & versions in the venv after install
      pip_package_info:
        clients: "/usr/local/lib/pulp/bin/pip"
      register: pip_pkgs
    - name: Assert pulpcore>=3.14.6, pulp-file>=1.8.2, pulp-container>=2.8.0
      assert:
        that:
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulpcore'][0].version is version("3.14.6", ">=")
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulp-file'][0].version is version("1.8.2", ">=")
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulp-container'][0].version is version("2.8.0", ">=")
    - name: Assert pulp-rpm>=3.14.12
      assert:
        that:
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulp-rpm'][0].version is version("3.14.12", ">=")
      when: ansible_facts.os_family == 'RedHat'
# Test upgrading to latest version (new branches but upgrade=false)
- hosts: all
  force_handlers: True
  tasks:
    - set_fact:
        pulpcore_version: "3.18"
        pulpcore_update: false
    - set_fact:
        pulp_install_plugins:
          pulp_file:
            version: "1.10"
            upgrade: false
          pulp_rpm:
            version: "3.17"
            upgrade: false
          pulp_container:
            version: "2.11"
            upgrade: false
      when: ansible_facts.os_family == 'RedHat'
    - set_fact:
        pulp_install_plugins:
          pulp_file:
            version: "1.10"
            upgrade: false
          pulp_container:
            version: "2.11"
            upgrade: false
      when: ansible_facts.os_family == 'Debian'
    - include_role:
        name: pulp_database_config
    - name: Obtain list of packages & versions in the venv after install
      pip_package_info:
        clients: "/usr/local/lib/pulp/bin/pip"
      register: pip_pkgs
    - name: Assert pulpcore>=3.18.0, pulp-file>=1.10.0, pulp-container >=2.11.0
      assert:
        that:
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulpcore'][0].version is version("3.18.0", ">=")
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulp-file'][0].version is version("1.10.0", ">=")
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulp-container'][0].version is version("2.11.0", ">=")
    - name: Assert pulp-rpm>=3.17.0
      assert:
        that:
          - pip_pkgs.packages['/usr/local/lib/pulp/bin/pip']['pulp-rpm'][0].version is version("3.17.0", ">=")
      when: ansible_facts.os_family == 'RedHat'
    - name: Show the output of container-repair-media-type
      debug:
        var: repair_pip
    - name: Assert that container-repair-media-type was run
      assert:
        that:
          - '"Successfully repaired" in repair_pip.stdout'
