---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    ansible-lint
# This is ignored by molecule, but can be reused in yaml
.platform_base: &platform_base
  privileged: False
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  tmpfs:
    # Fixes issues accessing .so files under /tmp during pip builds.
    # https://github.com/docker/compose/issues/1339
    - /tmp:exec,mode=1777
    - /run
    - /run/lock
  capabilities:
    - NET_ADMIN
    - NET_RAW
  pre_build_image: true
platforms:
  - <<: *platform_base
    name: centos-7
    # molecule often fails to pull, so we pull all images in .travis.yml
    image: quay.io/pulp/pulp_rpm-ci-c7:3.1.0
    command: /sbin/init
  - <<: *platform_base
    name: debian-11
    image: quay.io/pulp/pulp-ci-dbullseye:3.14.4
    command: /sbin/init
  - <<: *platform_base
    name: fedora-33
    image: quay.io/pulp/pulp_rpm-ci-f33:3.9.0
    command: /usr/sbin/init
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: $PWD/build/collections  # for ansible >= 2.10.0.dev0
    ANSIBLE_COLLECTIONS_PATHS: $PWD/build/collections
    ANSIBLE_VERBOSITY: 3
  config_options:
    defaults:
      stdout_callback: debug
      callback_enabled: profile_tasks
  inventory:
    links:
      host_vars: ../scenario_resources/host_vars/
scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
verifier:
  name: ansible
  directory: tests
