---
pulp_pkg_exclude: "python3-drf-yasg"  # Fixes upgrading from pre-3.8. It would depend on python3-django.
pulp_pkg_name_prefix: "python3-"
pulp_pkg_undeclared_deps:
  - "{{ pulp_pkg_name_prefix }}markuppy"  # Because of https://bugzilla.redhat.com/show_bug.cgi?id=1986965
  - "{{ pulp_pkg_name_prefix }}xlrd"
pulp_preq_packages:
  - python3
  - python3-devel
  - python3-libselinux  # For ansible itself
  - python3-policycoreutils  # For ansible itself
  - gcc                 # For psycopg2
  - make                # For make docs, and SELinux policy install
  - libpq-devel         # Renamed/Split version of postgresql-devel
  - git                 # For source install, and SELinux policy install
  - sudo
  - gnupg2              # For the signing service via the gpg python module

# Pulp requires Python 3.8+.
pulp_python_interpreter: /usr/bin/python3
pulp_python_cryptography:
  - python3-cryptography
# Used by galaxy_post_install, which doesn't have per-distro vars yet
__pulp_gpg_inspect_command: "gpg --import-options show-only --import --with-fingerprint"
