---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    ansible-lint
# This is ignored by molecule, but can be reused in yaml
.platform_base: &platform_base
  privileged: False
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  tmpfs:
    # Fixes issues accessing .so files under /tmp during pip builds.
    # https://github.com/docker/compose/issues/1339
    - /tmp:exec,mode=1777
    - /run
    - /run/lock
  capabilities:
    - NET_ADMIN
    - NET_RAW
  pre_build_image: true
platforms:
  - <<: *platform_base
    name: centos-7
    # molecule often fails to pull, so we pull all images in .travis.yml
    image: quay.io/pulp/pulp_rpm-ci-c7:3.1.0
    command: /sbin/init
  - <<: *platform_base
    name: debian-11
    image: quay.io/pulp/pulp-ci-dbullseye:3.14.4
    command: /sbin/init
  - <<: *platform_base
    name: centos-8
    image: quay.io/pulp/pulp_installer-pip-ci-c8:3.9.1
    command: /sbin/init
  - <<: *platform_base
    name: centos-stream9
    image: quay.io/pulp/pulp_installer-pip-ci-c9:3.13.0
    command: /sbin/init
  - <<: *platform_base
    name: fedora-36
    image: quay.io/pulp/pulp_installer-pip-ci-f36:3.13.0
    command: /usr/sbin/init
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: $PWD/build/collections:~/.ansible/collections:/usr/share/ansible/collections # for ansible >= 2.10.0.dev0
    ANSIBLE_COLLECTIONS_PATHS: $PWD/build/collections:~/.ansible/collections:/usr/share/ansible/collections
    ANSIBLE_CALLBACKS_ENABLED: "profile_tasks,profile_roles"
    CALLBACKS_ENABLED: "profile_tasks,profile_roles"
  config_options:
    defaults:
      stdout_callback: debug
      callback_enabled: profile_tasks
  inventory:
    links:
      group_vars: ../scenario_resources/group_vars/
scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # pip installing from source always replaces the installed version, thus
    # the task is always reports changed. During upgrades, we need the handlers
    # to run on the pip install tasks, so we can't alter said tasks to never
    # report changed. So let's just not run idempotency on this scenario.
    - check
    - side_effect
    - verify
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
  directory: tests
