---
molecule_images:
  - name: centos-7
    image: centos:7
    command: /sbin/init
  - name: centos-stream8
    image: centos:stream8
    command: /sbin/init
  - name: fedora-33
    image: fedora:33
    command: /usr/sbin/init
  - name: debian-10
    image: debian:10
    command: /sbin/init
