---
molecule_images:
  - name: centos-7
    image: centos:7
    command: /sbin/init
  - name: centos-stream8
    image: centos:stream8
    command: /sbin/init
  - name: fedora-34
    image: fedora:34
    command: /usr/sbin/init
  - name: debian-11
    image: debian:bullseye
    command: /sbin/init
