---
dependency:
  name: galaxy
# This yaml anchor is ignored by molecule, but can be reused in yaml
# It is ignored in the dependency section, and cannot be a top-level section
  .platform_base: &platform_base
    privileged: False
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      # Fixes issues accessing .so files under /tmp during pip builds.
      # https://github.com/docker/compose/issues/1339
      - /tmp:exec,mode=1777
      - /run
      - /run/lock
    capabilities:
      - NET_ADMIN
      - NET_RAW
    pre_build_image: true
driver:
  name: docker
lint: |
    ansible-lint
platforms:
  - <<: *platform_base
    name: centos-7
    # molecule often fails to pull, so we pull all images in .travis.yml
    image: quay.io/pulp/pulp-ci-pkgs-c7:3.7.9-1
    command: /sbin/init
  - <<: *platform_base
    name: centos-8
    image: quay.io/pulp/pulp-ci-pkgs-c8:3.7.9-1
    command: /sbin/init
  - <<: *platform_base
    name: centos-9
    image: quay.io/pulp/pulp-ci-pkgs-c9:3.18.5-1
    command: /sbin/init
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: $PWD/build/collections:~/.ansible/collections:/usr/share/ansible/collections # for ansible >= 2.10.0.dev0
    ANSIBLE_COLLECTIONS_PATHS: $PWD/build/collections:~/.ansible/collections:/usr/share/ansible/collections
    ANSIBLE_CALLBACKS_ENABLED: "profile_tasks,profile_roles"
    CALLBACKS_ENABLED: "profile_tasks,profile_roles"
  config_options:
    defaults:
      stdout_callback: debug
      callback_enabled: profile_tasks
  inventory:
    links:
      group_vars: ../scenario_resources/group_vars/
scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
verifier:
  name: ansible
  directory: tests
