---
name: Pulp Nightly CI
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '15 0 * * *'
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # Testing different python versions because of
      # https://pulp.plan.io/issues/5768#note-17
      matrix:
        include:
          - test_type: release-static
            ansible: "2.9"
            python: "2.7"
            toxpy: "27"
          - test_type: source-static
            ansible: "2.9"
            python: "3.6"
            toxpy: "36"
          - test_type: packages-static
            ansible: "2.10"
            python: "3.7"
            toxpy: "37"
          - test_type: release-dynamic
            ansible: "2.10"
            python: "3.8"
            toxpy: "38"
          - test_type: source-dynamic
            ansible: "2.9"
            python: "3.8"
            toxpy: "38"
          - test_type: packages-dynamic
            ansible: "2.9"
            python: "3.7"
            toxpy: "37"
          - test_type: release-upgrade
            ansible: "2.9"
            python: "2.7"
            toxpy: "27"
          - test_type: source-upgrade
            ansible: "2.10"
            python: "3.6"
            toxpy: "36"
          - test_type: packages-upgrade
            ansible: "2.10"
            python: "3.6"
            toxpy: "36"
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Pulling images for PyPI upgrades
        if: matrix.test_type == 'release-upgrade' || matrix.test_type == 'source-upgrade'
        run: |
          docker pull quay.io/pulp/pulp-ci-dbullseye:3.14.4
          docker pull quay.io/pulp/pulp_rpm-ci-f33:3.9.0
          docker pull quay.io/pulp/pulp_rpm-ci-c7:3.1.0
      - name: Pulling images for distro packages upgrades
        if: matrix.test_type == 'packages-upgrade'
        run: |
          docker pull quay.io/pulp/pulp-ci-pkgs-c7:3.3.1
          docker pull quay.io/pulp/pulp-ci-pkgs-c8:3.3.1
      - name: Run tox
        run: tox -e "py${{ matrix.toxpy }}-ansible${{ matrix.ansible }}-${{ matrix.test_type }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        shell: bash
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run publish docs script
      env:
        PULP_DOCS_KEY: ${{ secrets.PULP_DOCS_KEY }}
      run: .ci/scripts/publish_docs.sh ${GITHUB_REF##*/}
  vagrant:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - test_type: pulp3-source-centos8-fips
          - test_type: pulp3-source-centos7-fips
          - test_type: pulp3-source-fedora34
          - test_type: pulp3-source-debian11
          - test_type: pulp2-nightly-pulp3-source-centos7
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Vagrant
        shell: bash
        run: |
          .github/workflows/scripts/install.sh ${{ matrix.test_type }}
          # For the source tests
          cd ..
          git clone https://github.com/pulp/pulpcore
          git clone https://github.com/pulp/pulp_file
      - name: Run Vagrant
        shell: bash
        run: .github/workflows/scripts/script.sh ${{ matrix.test_type }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          TERM: 'xterm-256color'
      - name: After failure
        if: failure()
        run: .github/workflows/scripts/after_failure.sh ${{ matrix.test_type }}
